### PR TITLE
Publish to npm

### PR DESCRIPTION
**Pull request by HaNdTriX**
Hey @uzairfarooq

thanks for this nifty library!

I would be awesome to be able to install this lib via npm.
Therefore I added a package.json file.

Just run npm publish in your terminal to release it.

close #35

### CODE REVIEW

**Comment by HaNdTriX** [comment]
thanks!

**Comment by uzairfarooq** [comment]
I've just moved it to master and published the lib to npm (https://www.npmjs.com/package/arrive) but have noticed that you're not being shown in the Contributors list. Maybe because your email handtrix@gmail.com is not associated with your account?

screen shot 2015-10-03 at 10 34 09 pm

BTW, have you used the library in node.js? Just wondering how'd you use the library as there's no DOM in node.js and the library binds it's function to prototype of DOM elements.

**Comment by HaNdTriX** [comment]
Hey @uzairfarooq 
Thanks I have verified my second E-Mail!

I am not using this library with node.js. Even though I would be possible.

https://github.com/tmpvar/jsdom 

But I am using it with [browserify](http://browserify.org/) and [webpack](https://github.com/webpack/webpack).

**Comment by uzairfarooq** [comment]
Ah! thanks

**Pull request merged**
